from pybricks.tools import wait

async def run_6(robot):
    print("Starting Run: " + __name__)
    robot.Drive.settings(straight_speed=500)
    #await robot.Left_attach.run_angle(200, 45*-.77)
    robot.Left_attach.dc(35)
    await wait (1000)
    robot.Left_attach.stop()
    await robot.Left_attach.run_angle(200, -8)
    #await robot.Left_attach.run_angle(200, -45*-.77*-1)
    await robot.Drive.straight(-970)
    await robot.Drive.turn(-91)
    await robot.Right_attach.run_angle(150,-100)
    await robot.Left_attach.run_angle(240,117.6*-.77)
    robot.Drive.settings(straight_speed=50)

    #approach opening and lower arm to pickup precious artifact
    await robot.Drive.straight(55)
    await robot.Left_attach.run_angle(200,-12)

    # pickup precious artifact
    await robot.Drive.straight(67)
    await robot.Left_attach.run_angle(200,-14*-.77)
    await wait(500)
    await robot.Right_attach.run_angle(100,100)
    await robot.Drive.straight(-145)
    robot.Drive.settings(straight_speed=500)
    await robot.Drive.turn(90)
    await wait(500)
    await robot.Drive.turn(-45)
    await robot.Left_attach.run_angle(500,40*-.77)
    robot.Drive.settings(straight_speed=120)
    await robot.Drive.straight(390.5)
    robot.Drive.settings(straight_speed=41)
    robot.Left_attach.dc(-95*-1)
    await wait(600) 
    robot.Left_attach.stop()
    robot.Drive.settings(straight_speed=250)
    await robot.Drive.straight(-364.5)
    await robot.Drive.turn(45)
    await robot.Drive.straight(974)
